<?php

declare(strict_types=1);

namespace Miran\Mksine\Core\Services;

use Illuminate\Filesystem\Filesystem;

/**
 * Service responsible for caching hook state to a PHP file.
 *
 * This service handles:
 * - Writing resolved hook state to a cache file
 * - Reading cached hook state
 * - Cache invalidation
 *
 * The cache file is a simple PHP array for maximum performance (OpCache friendly).
 * Cache file: bootstrap/cache/mks_hook_state.php
 */
class HookCacheManager
{
    private Filesystem $filesystem;

    private string $cachePath;

    public function __construct(?Filesystem $filesystem = null, ?string $cachePath = null)
    {
        $this->filesystem = $filesystem ?? new Filesystem;
        $this->cachePath = $cachePath ?? base_path('bootstrap/cache/mks_hook_state.php');
    }

    /**
     * Get the cache file path.
     */
    public function getCachePath(): string
    {
        return $this->cachePath;
    }

    /**
     * Check if cached hook state exists.
     */
    public function exists(): bool
    {
        return $this->filesystem->exists($this->cachePath);
    }

    /**
     * Get cached hook state.
     * Returns the resolved state: enabled listeners with their effective priorities.
     *
     * @return array{enabled_state: array<string, bool>, priority_overrides: array<string, int>, system_flags: array<string, bool>}|null
     */
    public function get(): ?array
    {
        if (! $this->exists()) {
            return null;
        }

        try {
            $cached = require $this->cachePath;

            // Validate cache structure
            if (! is_array($cached) ||
                ! isset($cached['enabled_state']) ||
                ! isset($cached['priority_overrides']) ||
                ! isset($cached['system_flags'])) {
                $this->clear();

                return null;
            }

            return $cached;
        } catch (\Throwable $e) {
            // If cache file is corrupted, delete it and return null
            $this->clear();

            return null;
        }
    }

    /**
     * Write hook state to cache file.
     *
     * @param  array<string, bool>  $enabledState
     * @param  array<string, int>  $priorityOverrides
     * @param  array<string, bool>  $systemFlags
     */
    public function put(array $enabledState, array $priorityOverrides, array $systemFlags): bool
    {
        $directory = dirname($this->cachePath);

        // Ensure directory exists
        if (! $this->filesystem->exists($directory)) {
            $this->filesystem->makeDirectory($directory, 0755, true);
        }

        $cacheData = [
            'enabled_state' => $enabledState,
            'priority_overrides' => $priorityOverrides,
            'system_flags' => $systemFlags,
        ];

        $content = "<?php\n\n";
        $content .= "// This file is auto-generated by MKS CMS hook discovery system.\n";
        $content .= "// Do not edit manually. Run 'php artisan mks:discover' to regenerate.\n";
        $content .= '// Generated at: ' . date('Y-m-d H:i:s') . "\n\n";
        $content .= 'return ' . var_export($cacheData, true) . ";\n";

        return $this->filesystem->put($this->cachePath, $content, true) !== false;
    }

    /**
     * Clear the cache file.
     */
    public function clear(): bool
    {
        if ($this->exists()) {
            return $this->filesystem->delete($this->cachePath);
        }

        return true;
    }

    /**
     * Invalidate cache if it's older than the specified TTL or if hooks have been modified.
     *
     * Cache Invalidation Strategy:
     * - Check file modification time
     * - If cache is older than TTL (default: 1 hour), invalidate
     * - If database hooks have been modified (via mks_hooks table updated_at), invalidate
     *
     * @param  int  $ttlSeconds  Time-to-live in seconds (default: 3600 = 1 hour)
     * @return bool True if cache was invalidated, false if still valid
     */
    public function invalidateIfStale(int $ttlSeconds = 3600): bool
    {
        if (! $this->exists()) {
            return false; // No cache to invalidate
        }

        $cacheModifiedTime = $this->filesystem->lastModified($this->cachePath);
        $now = time();

        // Invalidate if cache is older than TTL
        if (($now - $cacheModifiedTime) > $ttlSeconds) {
            return $this->clear();
        }

        // Check if database hooks have been modified (if database is available)
        try {
            if (\Illuminate\Support\Facades\Schema::hasTable('mks_hooks')) {
                $latestHookUpdate = \Illuminate\Support\Facades\DB::table('mks_hooks')
                    ->max('updated_at');

                if ($latestHookUpdate) {
                    $hookUpdateTime = strtotime($latestHookUpdate);
                    // If hooks were updated after cache was created, invalidate
                    if ($hookUpdateTime > $cacheModifiedTime) {
                        return $this->clear();
                    }
                }
            }
        } catch (\Exception $e) {
            // If database check fails, don't invalidate (fail-safe)
            // Cache will be regenerated on next discovery
        }

        return false; // Cache is still valid
    }
}
