<?php

declare(strict_types=1);

namespace Miran\Mksine\Core\Services;

/**
 * Service responsible for caching hook discovery results.
 *
 * This service handles:
 * - Caching discovery results to a PHP file for performance
 * - Loading cached results in production environments
 * - Clearing cache when hooks are re-discovered
 *
 * Cache file: bootstrap/cache/mks_hook_discovery.php
 */
class HookDiscoveryCache
{
    private string $cachePath;

    public function __construct(?string $cachePath = null)
    {
        $this->cachePath = $cachePath ?? base_path('bootstrap/cache/mks_hook_discovery.php');
    }

    /**
     * Get the cache file path.
     */
    public function getCachePath(): string
    {
        return $this->cachePath;
    }

    /**
     * Check if cached discovery results exist.
     */
    public function exists(): bool
    {
        return file_exists($this->cachePath);
    }

    /**
     * Get cached discovery results.
     *
     * @return array{listeners: array, form_hooks: array, form_slot_hooks?: array, table_hooks: array}|null
     */
    public function get(): ?array
    {
        if (! $this->exists()) {
            return null;
        }

        try {
            return require $this->cachePath;
        } catch (\Throwable $e) {
            // If cache file is corrupted, delete it and return null
            $this->clear();

            return null;
        }
    }

    /**
     * Cache discovery results.
     *
     * @param  array{listeners: array, form_hooks: array, form_slot_hooks?: array, table_hooks: array}  $results
     */
    public function put(array $results): bool
    {
        $directory = dirname($this->cachePath);

        // Ensure directory exists
        if (! is_dir($directory)) {
            if (! mkdir($directory, 0755, true) && ! is_dir($directory)) {
                return false;
            }
        }

        $content = "<?php\n\n";
        $content .= "// This file is auto-generated by MKS CMS hook discovery system.\n";
        $content .= "// Do not edit manually. Run 'php artisan mks:discover' to regenerate.\n\n";
        $content .= 'return ' . var_export($results, true) . ";\n";

        return file_put_contents($this->cachePath, $content, LOCK_EX) !== false;
    }

    /**
     * Clear the discovery cache.
     */
    public function clear(): bool
    {
        if ($this->exists()) {
            return unlink($this->cachePath);
        }

        return true;
    }

    /**
     * Check if cache should be used based on environment.
     */
    public function shouldUseCache(): bool
    {
        // Use cache in production or when explicitly enabled
        if (function_exists('app')) {
            $env = app()->environment();

            return in_array($env, ['production', 'prod'], true);
        }

        // Default to false if we can't determine environment
        return false;
    }
}
